version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: db_orcamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: orcamento
      MYSQL_USER: foo
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"